[package]
name = "crow"
version = "0.1.0"
authors = ["JvG <jeffrey.vangeete@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crow = "0.7.1"