[package]
name = "proof_of_work"
version = "0.1.0"
authors = ["Jeff van Geete <jeff.vangeete@protectwise.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
